<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class CustomersRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => ['required'],
            'surname' => ['required'],
            'phone' => ['required'],
            'email' => ['required','email'],
            'password' => ['required','string'],
        ];
    }
    public function getValidatorInstance(): Validator
    {
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }

    protected function failedValidation(Validator $validator)
    {
        $response = [
            'status' => 'failure',
            'status_code' => 400,
            'message' => 'Bad Request',
            'payload' => $validator->errors(),
        ];

        throw new HttpResponseException(response()->json($response, 400));

    }
}
